// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXR6CM1GwCLKMGtm3l0r-Ju8Gla1d7ecs',
    appId: '1:964528002795:web:17061245755d1e9a36d0ae',
    messagingSenderId: '964528002795',
    projectId: 'gudangkita-544f2',
    authDomain: 'gudangkita-544f2.firebaseapp.com',
    storageBucket: 'gudangkita-544f2.firebasestorage.app',
    measurementId: 'G-R24TMMPQ9H',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfcOL2FE4W8k2maNtkmcKBv-EOJOpHxTM',
    appId: '1:964528002795:ios:7668ed451b23adbc36d0ae',
    messagingSenderId: '964528002795',
    projectId: 'gudangkita-544f2',
    storageBucket: 'gudangkita-544f2.firebasestorage.app',
    iosBundleId: 'com.example.uasInventory',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfcOL2FE4W8k2maNtkmcKBv-EOJOpHxTM',
    appId: '1:964528002795:ios:7668ed451b23adbc36d0ae',
    messagingSenderId: '964528002795',
    projectId: 'gudangkita-544f2',
    storageBucket: 'gudangkita-544f2.firebasestorage.app',
    iosBundleId: 'com.example.uasInventory',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJU1pFzzlffHnQEDqgIk-G_kuMPJf0eWM',
    appId: '1:964528002795:android:51cea229588d57d936d0ae',
    messagingSenderId: '964528002795',
    projectId: 'gudangkita-544f2',
    storageBucket: 'gudangkita-544f2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXR6CM1GwCLKMGtm3l0r-Ju8Gla1d7ecs',
    appId: '1:964528002795:web:53d66780db8c333b36d0ae',
    messagingSenderId: '964528002795',
    projectId: 'gudangkita-544f2',
    authDomain: 'gudangkita-544f2.firebaseapp.com',
    storageBucket: 'gudangkita-544f2.firebasestorage.app',
    measurementId: 'G-9PVD9FJ7SZ',
  );

}